from __future__ import annotations


def test_func1():
    raise Exception("test ran")
