def test_func():
    raise Exception("asdf")
